version: '3.8'
services:
    laravel.test:
        build: null
        context: ./vendor/laravel/sail/runtimes/8.3
        dockerfile: Dockerfile
        args:
            WWWGROUP: '${WWWGROUP}'
        depends_on:
            - mysql
            - mailpit
    image: sail-laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: always
        working_dir: /var/www
        volumes:
            - '.:/var/www'
        depends_on:
            - db
        networks:
            - laravel_network
    webserver:
        image: 'nginx:latest'
        container_name: nginx_server
        restart: always
        ports:
            - '8000:80'
        volumes:
            - '.:/var/www'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - app
        networks:
            - laravel_network
    db:
        image: 'mysql:8.0'
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_DATABASE: tsk_manager
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - '3306:3306'
        volumes:
            - 'db_data:/var/lib/mysql'
        networks:
            - laravel_network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: rootpassword
        ports:
            - '8080:80'
        depends_on:
            - db
            - mysql
            - mailpit
        networks:
            - laravel_network
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
networks:
    laravel_network: null
volumes:
    db_data: null
    sail-mysql:
        driver: local
